#!/bin/bash

USER=long
HOME=/home/$USER
declare -A map=( ["i3config"]="${HOME}/.config/i3/config" )

function bck {
    echo "Backing up $2..."
    cp -r --parents $1 bck/
}

echo
echo "--------------------------------------------------"
echo "Create Local Mirror Backup"
echo "--------------------------------------------------"

if [ ! -d bck ]; then
   mkdir bck
fi

for backup in "${!map[@]}"
do
    echo "Backing up ${map[$backup]} to bck/$backup..."
    cp -r ${map[$backup]} "bck/$backup"
done

echo 
echo "--------------------------------------------------"
echo "Clean up"
echo "--------------------------------------------------"
find . -name "*~" | xargs rm -v; find . -name "*#" | xargs rm
# rm mirror/home/$USER/.emacs.d/session.*
echo ""
echo "DONE!"
